syntax = "proto3";

package com.local.passover;

message Message{
  int64 timestamp_ms = 1;

  oneof payload{
    ClipboardMessage clipboard = 2;
    MediaControlMessage mediaControl = 3;
    MediaPlaybackInfo playbackInfo = 4;

    FileHeader fileHeader = 5;
    FileChunk fileChunk = 6;
    FileStatusRequest statusRequest = 7;
    FileStatusResponse statusResponse = 8;
    FileTransferError error = 9;

    VideoStreamChunk videoChunk = 10;
    MediaArt artwork = 11;
    Heartbeat heartbeat = 12;
    Identity identity = 13;
    QRPayload qrPayload = 14;
  }
}

message Identity{
  string deviceId = 1;
}

message QRPayload{
  string deviceId = 1;
  string key = 2;
}

message ClipboardMessage{
  string content = 1;
  enum ClipboardContentType{
    TXT = 0;
    IMG = 1;
  }
  ClipboardContentType type = 2;
}

message MediaControlMessage{
  enum Action{
    PLAY_PAUSE = 0;
    NEXT = 1;
    PREVIOUS = 2;
    VOLUME_SET = 3;
  }
  Action action = 1;
  float volume = 2;
}

message MediaArt{
  bytes content = 1;
}

message MediaPlaybackInfo{
  bool playbackRate = 1;
  double duration = 2;
  double elapsed = 3;
  string title = 4;
  string album = 5;
  string artist = 6;
  string bundle = 7;
  float volume = 8;
}

message FileHeader{
  string fileId = 1;
  string filename = 2;
  int64 filesizeBytes = 3;
  bytes metadata = 4;
}

message FileChunk{
  string fileId = 1;
  int64 offset = 2;
  bytes data = 3;
}

message FileStatusRequest{
  string fileId = 1;
}

message FileStatusResponse{
  string fileId = 1;
  int64 bytesRecieved = 2;
}

message FileTransferError{
  string fileId = 1;
  string error = 2;
}

message Heartbeat{
  bool isMediaPlaying = 1;
  bool isMacUserActive = 2;
}

message VideoStreamChunk{
  bytes frame = 1;
  int64 presentationTimestampUs = 2;
}